# fly.toml app configuration file generated for fsopart3lindsaynichols-hidden-bird-4765 on 2023-12-02T12:33:37-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fsopart3lindsaynichols-hidden-bird-4765"
primary_region = "lax"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
